all: mux mux_buff principal_np
mux: mux.c
	gcc -o mux mux.c
mux_buff: mux_buff.c
	gcc -o mux_buff mux_buff.c
	
principal_np: principal_np.c
	gcc -o principal_np principal_np.c
clean:
	rm mux mux_buff principal_np
