all: listaParametros punteros words

listaParametros: listaParametros.c
gcc -o listaParametros.exe listaParametros.c

punteros: punteros.c
gcc -o punteros.exe punteros.c

words: words.c
gcc -o words.exe words.c

clean:
rm listaParametros
rm punteros
rm words
