# (c) FIBerHub, https://fiberhub.tk

all: ejemplo_alarm2 bucleInfinito ejemplo_alarm3 ejemplo_signal ejemplo_signal2 eventos eventos2 signal_perdido2

ejemplo_alarm2: ejemplo_alarm2.c
	gcc -o ejemplo_alarm2 ejemplo_alarm2.c
bucleInfinito: bucleInfinito.c
	gcc -o bucleInfinito bucleInfinito.c
ejemplo_alarm3: ejemplo_alarm3.c
	gcc -o ejemplo_alarm3 ejemplo_alarm3.c
ejemplo_signal: ejemplo_signal.c
	gcc -o ejemplo_signal ejemplo_signal.c
ejemplo_signal2: ejemplo_signal2.c
	gcc -o ejemplo_signal2 ejemplo_signal2.c
eventos: eventos.c
	gcc -o eventos eventos.c
eventos2: eventos2.c
	gcc -o eventos2 eventos2.c
signal_perdido2: signal_perdido2.c
	gcc -o signal_perdido2 signal_perdido2.c
	
clean:
	rm ejemplo_alarm2
	rm bucleInfinito
	rm ejemplo_alarm3
	rm ejemplo_signal
	rm ejemplo_signal2
	rm eventos
	rm eventos2
	rm signal_perdido2